[package]
name = "samp-udp-proxy"
version = "1.0.0"
authors = ["Arron (Michael) Franklin"]
edition = "2018"

[dependencies]
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.3.1"
rand = "0.6.5"